version: '3'
services:
  production:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SERVICE_ENV=production

  test:
    build: ./
    ports:
      - "8009:8000"
    env_file:
      - .env
    environment:
      - SERVICE_ENV=test
